[build]
# Use Docker instead of Nixpacks
builder = "DOCKERFILE"

[deploy]
# Docker handles the start command, so we don't need this
# The ENTRYPOINT in Dockerfile will handle starting the app
# startCommand = "dotnet out/IvyScans.API.dll"  # Remove this line
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
# Production environment variables
[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

[environments.staging]
# Staging environment variables  
[environments.staging.variables]
ASPNETCORE_ENVIRONMENT = "Staging"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

# Optional: Specify .NET version
[build.nixpacksConfig]
providers = ["dotnet"]

[build.nixpacksConfig.dotnet]
version = "9.0"