[build]
# Build command for .NET 9
builder = "NIXPACKS"
buildCommand = """
cd IvyScans/Back/IvyScans.API
dotnet restore
dotnet publish --configuration Release --output ../../../out --no-restore
"""

[deploy]
# Start command
startCommand = "dotnet out/IvyScans.API.dll"
# Health check endpoint (optional)
healthcheckPath = "/health"
# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
# Production environment variables
[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

[environments.staging]
# Staging environment variables  
[environments.staging.variables]
ASPNETCORE_ENVIRONMENT = "Staging"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

# Optional: Specify .NET version
[build.nixpacksConfig]
providers = ["dotnet"]

[build.nixpacksConfig.dotnet]
version = "9.0"